### ISSUE TITLE
Re-Flashing v2.3 Issue

### ISSUE THREAD

**Issue by shan224** [emlid/reach-docs#14]
After flashing the reach using the intel tool. The reach flashes between green and magenta indicators and is unaccessible via the intel tool.

Even on reboot the reach will get stuck between green and magenta

Any attempts to reflash the image using 1.2 or 2.3 result in the same outcome via intel tool and command line. 

I've only had this issue after trying to upgrade to 2.3, I can no longer even use version 1.2

**Comment by egorf** [comment]
Hi!

This behavior is OK. Magenta flashing means that Reach is trying to sync time. It can be done either by connecting it to the Internet or by lettings it sync with GPS. That will require connecting an antenna and some satellite visibility(putting the antenna out of the window is fine).

As soon as the time is synced, LED will just be green. You can connect to the hotspot and go to `http://192.168.42.1` to see the status.
