### ISSUE TITLE
acess to IMU data

### ISSUE THREAD

**Issue by olmerg** [emlid/reach-docs#2]
how to acess to IMU data or links to development with edinson. 
in http://docs.emlid.com/reach/software-development/

**Comment by ivereninov** [comment]
This is a work in progress. We will soon add IMU driver and logging functionality and update the docs accordingly.

**Comment by fgnievinski** [comment]
Quoting from the [forum](https://community.emlid.com/t/imu-data-from-reach-kit/1743/11):

> If you would like to get the data from the IMU until we implement it in ReachView MPU9250 is available on /dev/spidev5.1 and driver is located in /home/reach/MPUtest . Copy it from there, do not modify it in that directory.

**Comment by pedro1713** [comment]
Is there a ETA for adding the IMU functionality to the ReachView App?
