### ISSUE TITLE
Access to reach app without wireless network

### ISSUE THREAD

**Issue by sixtemesseven** [emlid/reach-docs#3]
Currently the reach app works over a wifi/ethernet router (as far as I can see). But since a wireless network is difficult to set up in the field it would be great if one could connect directly to the reach module using for example edisons access point functionality....

**Comment by ivereninov** [comment]
This is already implemented. If Reach does not see a familiar network it switches to hotspot mode automatically.

**Comment by sixtemesseven** [comment]
Thank you for your quick replay!
