### ISSUE TITLE
Firmware reflashing version too old

### ISSUE THREAD

**Issue by miquelmassot** [emlid/reach-docs#31]
The latest version AFAIK is 2.9. However, reflashing page directs you to 2.3.

**Comment by dimaershov** [comment]
Hi, 
We are currently working on preparing the new image for docs, it will be updated soon. 

Thanks!

**Comment by dimaershov** [comment]
Reach Image version is updated in docs:
https://docs.emlid.com/reach/common/reachview/firmware-reflashing/
