### ISSUE TITLE
64bit release of rtkpost?

### ISSUE THREAD

**Issue by Firefishy** [emlid/reach-docs#32]
Any chance you could build a 64bit release of RTKPOST? The memory limits on the 32bit release are quite tight.

https://github.com/emlid/reach-docs/blob/master/docs/common/tutorials/gps-post-processing.md

**Comment by egorf** [comment]
@Firefishy 

We plan to soon update our builds and will try to build the 64bit versions as well. Can't promise anything until we try, though.

**Comment by wittich** [comment]
64bit version would be create! That would save a lot of work with splitting the obs files!

**Comment by gnss-rider** [comment]
We really need 64 bit RTKPOST asap, current 32 bit version is too limited

**Comment by dimaershov** [comment]
Hey there, 

64bit version is available here:
https://docs.emlid.com/reach/common/tutorials/gps-post-processing/
