### ISSUE TITLE
PPP 

### ISSUE THREAD

**Issue by gnss-rider** [emlid/reach-docs#34]
Dear all, when will Correction input\Additional correction\precise ephemeris and clocks corrections be implemented in ReachView?
This feature is really key for standalone precise positioning and it will truly make the difference using Reach rather than any concurrent product.
This functionality will make Reach competitive even against traditional multi-frequency GNSS devices!
The functionality does not require big work at all to be implemented. Can this feature be prioritized?
Thank you!!

**Comment by staroselskii** [comment]
@gnss-rider 

Hello there!

This kind of questions are better suited for our [forum](community.emlid.com).
