### ISSUE TITLE
LED status description

### ISSUE THREAD

**Issue by sixtemesseven** [emlid/reach-docs#4]
Could you please include a list in the wiki with the meaning of all the LED blink patterns?

**Comment by kk6mrp** [comment]
I would also like the LED blink patterns if possible.

**Comment by kk6mrp** [comment]
I believe this issue can be closed

**Comment by sixtemesseven** [comment]
Where did they put the description?

**Comment by kk6mrp** [comment]
https://github.com/emlid/reach-docs/blob/master/docs/reachview-app.md#reading-led-status or http://docs.emlid.com/reach/reachview-app/#reading-led-status

They are both the same.

**Comment by sixtemesseven** [comment]
Great! Thank you! :)

**Comment by andersonpaac** [comment]
Both the links are now broken. are there links to this place or do we not have docs for this yet?

**Comment by kk6mrp** [comment]
Links Updated.
