### ISSUE TITLE
Custom NMEA output for Ardupilot

### ISSUE THREAD

**Issue by sixtemesseven** [emlid/reach-docs#5]
Reach Rover currently outputs NMEA messages:  GSA,  GGA, GSV, RMX
I think this is the reason why my Pixhawk is not recognizing the reach module. Settings: Output 38400 baud, NMEA.

(???)

Because I found this discussion:
http://diydrones.com/forum/topics/send-nmea-sentences-to-pixhawk-serial-port-e

Which says Ardupilot needs the messages: GGA, VTG, RMC in order to interpret the GPS module as NMEA input source. The format: 8bit, 1 stop, no parity seems to be in order.

Could you implement a NMEA-Ardupilot option in the Rover serial output selection with the correct messages? That would be great!!!

**Comment by ivereninov** [comment]
Thanks for the tip. I am sure that we had it working with NMEA messages present in Reach but we will have a deeper look into it once we get to the integration.

**Comment by sixtemesseven** [comment]
Last weekend I actually got a GCS message from the Reach module on Pixhawk`s 2and GPS channel:
gps2status: 1
gps2hdop: 99
So It sees something but no look despite having satellites. 


Btw. is it possible to set the rover module to receive correction signals on rx with eg. 57600 baud and simultaneously sending nmea at 38400 baud?

**Comment by ivereninov** [comment]
We are now working on a custom binary protocol to integrate with APM autopilots (Navio,Pixhawk etc..), so I am closing this for now. You can only have one baudrate on a UART port.
